In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv('data.csv')
X = pd.get_dummies(df.drop(['O'], axis=1))
y = df['O']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)
y_train.head()

13    14
10    11
12    11
8     15
7      9
Name: O, dtype: int64

In [17]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score
from tensorflow.keras.optimizers import Adam
import tensorflow as tf


# Instantiate the optimizer with the custom learning rate schedule
optimizer = Adam(learning_rate=0.1)

model = Sequential()
model.add(Dense(units=3, activation='relu', input_shape=(3,)))
model.add(Dense(units=6, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer=optimizer, loss='mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [19]:
'''class WO(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epock, logs=None):
        for i, layer in enumerate(model.layers):
            weights, biases = layer.get_weights()
            print("\nW ", weights)
            print("B ", biases);'''
#callbacks=[WO()]
model.fit(X_train, y_train, epochs=20, )

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.7550
W  [[-0.66301614 -0.18478145  1.0320156 ]
 [-0.68072146  0.24813691  0.74439025]
 [-0.28279516  0.25070983 -0.30548927]]
B  [-0.5366165   0.11069012  0.16858056]

W  [[ 0.1836735   0.00608002 -0.719997    0.2486595   0.15279257 -0.60129935]
 [ 0.14344656 -1.0937803  -0.21583831  0.42779177  0.0591782   0.33156872]
 [-0.70795095 -0.39248446 -0.53281105  1.1079191  -1.0954264  -0.93799   ]]
B  [ 0.         -0.82324463  0.          0.5996266  -0.38090664 -0.22771247]

W  [[ 0.5294833 ]
 [-0.07826073]
 [-0.893977  ]
 [ 0.8412221 ]
 [-0.2988871 ]
 [ 0.18506199]]
B  [0.7123291]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.7550
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 1.3421
W  [[-0.66873896 -0.18729219  1.0378203 ]
 [-0.6864443   0.24222638  0.74664295]
 [-0.28851798  0.24195814 -0.30498418]]
B  [-0.5423393   0.10270134  0.16406041]

W  [[ 1.8367350e-01  3.5720598e-04 -7.1999699e-01  2.5438231e-01
   1.527925

In [22]:
y_hat = model.predict(X_test)

test = pd.DataFrame({
    'i1': [1],
    'i2': [7],
    'i3': [5]
})

print(model.predict(test))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[[8.204783]]


In [61]:
model.save('tfmodel')

ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=tfmodel.

In [ ]:
del model

In [ ]:
model = load_model('tfmodel')